# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json

AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for creating Secrets Manager secret for parking management project"

Resources:
  ParkingManagementSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "parking-management-secret"
      Description: "Secrets for parking management application"
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: "JWT_SECRET"
        PasswordLength: 32
        ExcludePunctuation: true